### ISSUE TITLE
Yaml loading deprecation

### ISSUE THREAD

**Issue by LoyVanBeek** [floweisshardt/atf#136]
I got this error:
`/home/lvb/git/care-o-bot/src/atf/atf_core/src/atf_core/configuration_parser.py:181: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. 
Please read https://msg.pyyaml.org/load for full details.
  doc = yaml.load(stream)`

which points to https://msg.pyyaml.org/load

**Comment by fmessmer** [comment]
is fixed in https://github.com/floweisshardt/atf/pull/169/commits/6246cfebde920d9eaf231f9591c3cc1d18ae6c8c (see #169)
