### ISSUE TITLE
atf cannot be used from install space

### ISSUE THREAD

**Issue by fmessmer** [floweisshardt/atf#175]
because the cmake macro tries to run `generate_tests.py` from `@(CMAKE_SOURCE_DIR)/scripts/generate_tests.py`

```
  Errors     << mojin_atf_kevin:cmake /root/target_ws/logs/mojin_atf_kevin/build.cmake.000.log
  ATF: executing test generation macro with 'atf/test_generation_config.yaml' and EXECUTE_TESTS=True
  /usr/bin/python2: can't open file '/root/git/app_ws/src/atf/atf_core/scripts/generate_tests.py': [Errno 2] No such file or directory
  CMake Error at /root/git/app_ws/install/share/atf_core/cmake/atf_core-extras.cmake:39 (message):
    -- ATF: generating test files failed: exit_code='2'
  Call Stack (most recent call first):
    CMakeLists.txt:27 (atf_test)
```

**Comment by fmessmer** [comment]
in travis, we use `atf` in the `UPSTREAM_WORKSPACE` (via rosinstall), `UPSTREAM_WORKSPACE` is installed and used as underlay for `TARGET_WORKSPACE`
in gha, we have `atf` from the workspace on the docker image, which has `atf` installed - but also the `src` space removed!

so even if `atf` is installed in the `UPSTREAM_WORKSPACE` it still calls `generate_tests.py` from the source space

**Comment by floweisshardt** [comment]
maybe the catkin env variables might help here: http://docs.ros.org/en/jade/api/catkin/html/user_guide/variables.html
see usage in libpcan https://github.com/ipa320/cob_extern/blob/indigo_dev/libpcan/CMakeLists.txt#L6
