### ISSUE TITLE
test fails for several testblocksets that are not used

### ISSUE THREAD

**Issue by superseppl** [floweisshardt/atf#180]
Hi guys, 

If I define several testblocksets and only start one in the application script, this test fails even though it succeeds on all metrics. If I comment out all other testblocksets and run the analyzer again, it succeeds.

For example:  
In `testblocksets` in `testblock_1.yaml` I define: 
  * testblock_1: ...
  * testblock_2: ...

and start it in  `application.py`:
  * self.atf.start(testblock_1) 

The test will fail.

But if I define in `testblocksets` in `testblock_1.yaml`:
  * testblock_1: ...
 
and start it in `application.py`:
  * self.atf.start(testblock_1) 

The test will succeed.

**Comment by floweisshardt** [comment]
@superseppl thanks for your feedback. 

I think there's nothing wrong with the behaviour you described. Failing the overall test is the intended behaviour if you define a testblock that is not used. If desired testblocks are not executed this might indicate that your application.py is doing something wrong and thus should be catched via the ATF analyser.
